### ISSUE TITLE
Avoid function with side effects

### ISSUE THREAD

**Issue by mnkyjs** [Gila-Johanna-Hofmann/moody-colours#1]
It's good practice to avoid site effects in any part of your application. For example in your function, you have the parameters r,g,b and you assign them with a new value. This is not good practice, it would be better if you store this new value in a new variable and instead of returning the "site-effect" value/variable you should return the new value/variable.

Feel free to let me know if you need some more explaining for this topic.

### Example
`
const convertRedToHex = r.toString(16);
`

https://github.com/Gila-Johanna-Hofmann/moody-colours/blob/5afcf2f8ce7942bad092178267e0c839452244a7/scripts.js#L15

**Comment by Gila-Johanna-Hofmann** [comment]
thanks! I didn't know that!
